PR for review
visva-dev/Weather-App pull request #2
Opened 2020-12-09 08:18 UTC by visva-dev

## Weather App
- The Weather App project comes at the end of the Asynchronous Javascript and APIs section of the Javascript course.
- It tests the knowledge of the student about asynchronous communication with promises or async/await and when to use them.
- Users can get weather information using API.

2020-12-09 10:30 UTC, mikenath223 requested changes
### Hello @visva-dev  👋

**You've done quite on this. 💪**

However, let's make a few changes.

- [x]  Please add a toggle button so the user would be able to toggle between Celsius and Fahrenheit temperature states.

- [ ] OPTIONAL - You can add a loading animation to display before the data loads.

- [ ]  Kindly refer to other comments on your code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-12-09 10:32 UTC, mikenath223 commented on src/index.js
> +
- [ ] Please break up this code. You shouldn't dump all your code in `index.js`. **Separate logic code from DOM manipulation code into different modules.** Kindly do that.

2020-12-09 10:33 UTC, mikenath223 commented on src/index.js
> +
- [ ] You should also have a way to handle errors from the fetch request perhaps by chaining a `catch`  or using `try/catch block`.

2020-12-09 10:34 UTC, mikenath223 commented on package.json
> +  },
- [ ] Kindly add other necessary scripts in this section:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2020-12-09 10:35 UTC, mikenath223 commented on src/index.js
> +    ];
- [ ] Also please use ES6 arrow function syntax. **Fix this and other similar functions.**

2020-12-10 14:21 UTC, rOluochKe approved these changes
Hello @visva-dev 
### You got it right, well done. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-12-10 14:25 UTC, merged